<?php

define( 'TSB_DEFAULT_SIDEBAR_SELECTOR', '.region-sidebar-second' );
define( 'TSB_DEFAULT_MAIN_REGION_SELECTOR', '.region-content' );
define( 'TSB_DEFAULT_MAIN_REGION_CLASS_COLLPASED', 'col-sm-12' );
define( 'TSB_DEFAULT_MAIN_REGION_CLASS_EXPANDED', 'col-sm-9' );
define( 'TSB_DEFAULT_ICON_POSITION', 'right' );

/**
 * Implements hook_init().
 */
function cyco_toggle_sidebar_init() {
  // Try to load the cookie library, and check if that worked.
  $library = libraries_load('jquery-cookie');
  if ( empty($library['loaded']) || ! $library['loaded'] ) {
    $message = __FILE__ . ' (line ' . __LINE__ . ') ' . __FUNCTION__ 
        . ' jquery-cookie library missing';
    cyco_core_handle_error( $message );
  }
  $settings = array(
    'tsbSidebarSelector' => 
        variable_get(
            'tsb_sidebar_selector', 
            TSB_DEFAULT_SIDEBAR_SELECTOR
        ),
    'tsbMainRegionSelector' => 
        variable_get(
            'tsb_main_region_selector', 
            TSB_DEFAULT_MAIN_REGION_SELECTOR
        ),
    'tsbMainRegionClassWhenExpanded' => 
        variable_get(
            'tsb_main_region_class_when_expanded', 
            TSB_DEFAULT_MAIN_REGION_CLASS_EXPANDED
        ),
    'tsbMainRegionClassWhenCollapsed' => 
        variable_get(
            'tsb_main_region_class_when_collapsed', 
            TSB_DEFAULT_MAIN_REGION_CLASS_COLLPASED
        ),
    'tsbIconPosition' => 
        variable_get(
            'tsb_icon_position', 
            TSB_DEFAULT_ICON_POSITION
        ),
  );
  drupal_add_js(
      array('toggleSidebar' => $settings),
      array('type' => 'setting', 'every_page' => TRUE, 'weight' => -10)
  );
  drupal_add_js( 
      drupal_get_path('module', 'cyco_toggle_sidebar') 
        . '/js/cyco_toggle_sidebar.js',
      array('type' => 'file', 'every_page' => TRUE, 'weight' => 10)
  );
}

/**
 * Implements hook_menu.
 */
function cyco_toggle_sidebar_menu() {
  $items = array();
  $items['admin/config/cyco/cyco-toggle-sidebar'] = array(
    'title' => 'Toggle sidebar',
    'description' => 'Configure the toggle sidebar widget.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_tsb_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'cyco_toggle_sidebar.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}


/**
 * Implements hook_libraries_info().
 */
function cyco_toggle_sidebar_libraries_info() {
  $libraries = array();
  $libraries['jquery-cookie'] = array(
    'name' => 'JQuery cookie',
    'vendor url' => 'https://github.com/carhartl/jquery-cookie',
    'download url' => 'https://github.com/carhartl/jquery-cookie',
    'version arguments' => array(
      'file' => 'jquery.cookie.js',
      //  * jQuery Cookie Plugin v1.4.0
      'pattern' => '/plugin\s+v(.+?)$/im',
      'lines' => 10,
    ),
    'files' => array(
      'js' => array(
        'jquery.cookie.js',
      ),
    ),
  );
  return $libraries;
}
