<?php

/**
 * @file
 * Makes the nav bar that is at the bottom of each book page to also
 * appear at the top.
 */

//Default number of characters before navigation bar appears.
define('BOOK_TOP_NAVBAR_DEFAULT_MIN_CHARS', 500);
//Default for whether ToC is shown.
define('BOOK_TOP_NAVBAR_DEFAULT_SHOW_TOC', FALSE);
//Weight for the top nav bar. Book module uses 100 for the bottom bar.
define('BOOK_TOP_NAVBAR_NAV_BAR_WEIGHT', -10);
//Names of content fields to check for length.
define('BOOK_TOP_NAVBAR_CONTENT_FIELD_NAMES', 'body field_body');

/**
 * Implementation of hook_menu().
 */
function book_top_navbar_menu() {
  $items['admin/config/user-interface/book-top-navbar'] = array(
    'title' => 'Book top navbar settings',
    'description' => 'Change how the top navigation bar for books behaves',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('book_top_navbar_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'book_top_navbar.admin.inc',
  );
  return $items;
}

/**
 * Implementation of hook_node_view().
 *
 */
function book_top_navbar_node_view($node, $view_mode, $langcode) {
  if ( $view_mode == 'full' ) {
    //Is there book navigation for this code?
    if ( isset($node->content['book_navigation']) ) {
      //Find the main content field for the node.
      $field_name = _book_top_navbar_find_field( $node->content );
      if ( is_null($field_name) ) {
        //Didn't find a candidate field.
        watchdog(
          'Book top navbar', 
          'Couldn\'t find a content field, for node ' . $node->nid . '. '
            . ' Check the content field names in the administration form.'
        );
        return;
      }
      $content = strip_tags($node->content[$field_name][0]['#markup']);
      //Test for minimum length.
      if (drupal_strlen($content) >= variable_get('book_top_navbar_min_content_length',
                                    BOOK_TOP_NAVBAR_DEFAULT_MIN_CHARS)) {
        //To omit table of contents, force no children.
        $n = $node->book;
        //Turn off the ToC if configured that way.
        if ( ! variable_get('book_top_navbar_show_toc', BOOK_TOP_NAVBAR_DEFAULT_SHOW_TOC) ) {
          $n['has_children'] = FALSE;
        }
        //Add the nav bar.
        $node->content['book_navigation_top'] = array(
            '#markup' => theme('book_navigation', 
                array('book_link' => $n)),
            '#weight' => ( $node->content[$field_name]['#weight'] - 1 ) //book_top_navbar_NAV_BAR_WEIGHT,
        );
      }
    }
  }
}

/**
 * The main content field for the node will probably be body, but 
 * it might not be. The body field could have been deleted. So, 
 * look for a candidate, using the variable 
 * 'book_top_navbar_content_field_names' as a guide. This is set on the 
 * admin form.
 * 
 * @param array $content_fields Content field array for check.
 * @return string/null Name of first content field found, or NULL if none found.
 */
function _book_top_navbar_find_field( $content_fields ) {
  $potential_field_names = explode(
      ' ', 
      variable_get('book_top_navbar_content_field_names', 
            BOOK_TOP_NAVBAR_CONTENT_FIELD_NAMES)
  );
  foreach ( $potential_field_names as $potential_field_name ) {
    if ( isset( $content_fields[ $potential_field_name ][0]['#markup'] ) ) {
      return $potential_field_name;
    }
  }
  //Didna' find it, lassie!
  return NULL;
}

/**
 * Implementation of hook_help().
 */
function book_top_navbar_help($path, $arg) {
  switch ($path) {
    case 'admin/config/user-interface/book-top-navbar':
      return '<p>'.t("The book top navbar module takes the navigation bar that
appears at the bottom of each book page, and repeats it at the top of the
page.").'</p>';
    case 'admin/help#booktopnav':
      return
  '<p>'.t("The book top navbar module takes the navigation bar that
appears at the bottom of each book page, and repeats it at the top of the
page. This can be especially useful for users who are scanning a book,
looking for something they have seen before.").'</p>'
.'<p>'.t("You can specify whether the table of contents is shown in the
top navigation bar. You can also specify
how long a page must be before the navigation bar is added.
Repeated navigation can look strange on short pages.");
  }
}

